feat: add page to check the PR results in this repo
kulkultech/open-source pull request #31
Opened 2020-11-09 09:44 UTC by galanggg

Hi everyone, this is my PR to calculate how many PR has been done in this repo
Preview [Link](https://raw.githack.com/galanggg/open-source/76325c5a890d89629f85f939223a52bba1d66067/en_ID/pages/pr-check.html)

2020-11-09 09:46 UTC, galanggg commented
but i have some problem with coma when results comes out, like this
![localhost_5000_en_ID_pages_pr-check](https://user-images.githubusercontent.com/21099312/98525483-7a395480-22b3-11eb-9d7c-ddc587f422aa.png)

2020-11-09 09:48 UTC, empeje requested changes

2020-11-09 09:48 UTC, empeje commented on en_ID/pages/internship.md
> +Because these steps are simple, we expect high-quality work, which may take a longer time. We want to see that you are capable of using or learning how to use these tools (writing good GitHub issues,
I think you can add the link in the navigation menu as well.

2020-11-09 09:48 UTC, empeje commented on en_ID/pages/assets/script.js
> +    resultsContainer.innerHTML = loop
So the loop is an array of string, if you do the `resultsContainer.innerHTML = loop` directly the comma that coming from the array is inherited.

2020-11-09 12:24 UTC, galanggg commented
here the update [preview](https://raw.githack.com/galanggg/open-source/ec345d6d5575049c567718471e002fb2894ab2e4/en_ID/#!pages/progress.md)

2020-11-09 12:28 UTC, empeje commented
Tanks @galanggg, your PR is amazing, the next step is how to display a summary

e.g.

PR 4/5
Issues 3/4
Comments 4/4

2020-11-09 12:35 UTC, galanggg commented
> Tanks @galanggg, your PR is amazing, the next step is how to display a summary
> 
> e.g.
> 
> PR 4/5
> Issues 3/4
> Comments 4/4

Thanks for the feedback @empeje , i will try for the summary !

2020-11-10 09:52 UTC, empeje commented
Hi @galanggg any update on the summary?

Something simple like the following is enough

```
Progress for empeje:
Number of Comments: 0

Number of Issues: 0

Number of Merged PRs: 0

```

2020-11-10 10:36 UTC, galanggg commented
> Hi @galanggg any update on the summary?
> 
> Something simple like the following is enough
> 
> ```
> Progress for empeje:
> Number of Comments: 0
> 
> Number of Issues: 0
> 
> Number of Merged PRs: 0
> ```

hi @empeje , im still working on it :smile:

2020-11-10 12:08 UTC, empeje approved these changes
Looks good 🎉

2020-11-10 12:08 UTC, merged